Добавляет компонент для  сортировки
htmlacademy-react/814221-six-cities-5 pull request #9
Opened 2020-11-13 11:04 UTC by kazhurka

2020-11-14 10:40 UTC, klimnikova requested changes
По поводу селектора уже написала тебе

2020-11-14 10:40 UTC, klimnikova commented on src/store/reducer.js
>  };
вот так не надо делать. То есть у тебя стейт должны быть только простые сериализуемые объекты, массивы и примитивы, иначе возможны какие-то нежеланные побочные эффекты

2020-11-14 10:40 UTC, klimnikova commented on src/components/sorting-methods/sorting-methods.jsx
> +  offers: filterOffersBySort(state, state.sortType),
вот здесь тебе офферы не нужны

2020-11-14 10:40 UTC, klimnikova commented on src/components/cities-list/cities-list.jsx
> +              <SortingMethods></SortingMethods>
Пустой компонент - самозакрывающийся

2020-11-17 09:48 UTC, klimnikova approved these changes

2020-11-17 09:48 UTC, klimnikova commented on src/components/cities-list/cities-list.jsx
>    constructor(props) {
критерий Д11, необходимо переписать на функциональный компонент

2020-11-17 09:48 UTC, klimnikova commented on src/components/cities-list/cities-list.jsx
> -    const {changeCity, getOffers, offersAll} = this.props;
onClick, l опять в upper case

2020-11-17 09:48 UTC, klimnikova commented on src/components/cities-list/cities-list.jsx
> +              <SortingMethods onTabClick = {this._onTabClick}></SortingMethods>
пустой компонент самозакрывающийся

2020-11-17 09:48 UTC, klimnikova commented on src/store/selectors/get-filter-offers.js
> +          return offers.sort((a, b) => b.rate - a.rate);
давай сделаем вот что, чтобы все нормально работало ( в каждом кейсе) : return [...offers].sort и дальше все то же самое

2020-11-17 09:48 UTC, klimnikova commented on src/components/sorting-methods/sorting-methods.jsx
> +
const [opened, setOpened]

2020-11-17 09:48 UTC, klimnikova commented on src/store/selectors/get-filter-offers.js
> +          return offers.sort((a, b) => a.price - b.price);
еще надо будет вынести в перечисление виды сортировок

2020-11-17 09:48 UTC, merged

2020-11-17 09:51 UTC, kazhurka commented on src/components/cities-list/cities-list.jsx
> -    const {changeCity, getOffers, offersAll} = this.props;
да что-же за болезнь такая